[package]
name = "ergoap"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "ai", "goap", "utility", "ergonomic"]
categories = ["game-development"]
repository = "https://github.com/isidornygren/ergoap"
description = "an implementation of a GOAP (Goal Oriented Action Planning) system with focus on ergonomics and ease-of-use."
readme = "README.md"

[workspace]
members = ["macros"]

[dependencies]
bevy_app = { version = "0.18.0" }
bevy_ecs = { version = "0.18.0" }
bevy_reflect = { version = "0.18.0" }
bevy-trait-query = "0.18.0"
thiserror = "2.0.17"
inventory = "0.3.21"
ergoap_macros = { path = "./macros", version = "0.1.0" }
fxhash = "0.2.1"
bitvec = "1.0.1"

[dev-dependencies]
bevy = { version = "0.18.0", default-features = false, features = [
    "2d",
    "debug",
] }
criterion = "0.8.1"
seq-macro = "0.3.6"

[lints.clippy]
all = "warn"
correctness = "deny"
suspicious = "warn"
complexity = "warn"
nursery = "warn"
perf = "warn"
style = "warn"
pedantic = { level = "warn", priority = -1 }
new-ret-no-self = { level = "allow", priority = 1 }
type-complexity = { level = "allow", priority = 1 }
match-wildcard-for-single-variants = { level = "allow", priority = 1 }
enum-variant-names = { level = "allow", priority = 1 }
needless_pass_by_value = { level = "allow", priority = 1 }
derive-ord-xor-partial-ord = { level = "allow", priority = 1 }

[[bench]]
name = "bench"
harness = false

[profile.bench]
debug = true

[[example]]
name = "basic"
path = "examples/basic/main.rs"
resolver = "3"
required-features = ["target", "utility"]

[features]
target = []
utility = []
default = ["target", "utility"]
