[package]
name = "utility-goap"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["macros"]

[dependencies]
bevy_app = { version = "0.18.0" }
bevy_ecs = { version = "0.18.0" }
bevy_reflect = { version = "0.18.0" }
bevy-trait-query = "0.18.0"
thiserror = "2.0.17"
inventory = "0.3.21"
macros = { path = "macros" }

[dev-dependencies]
bevy = { version = "0.18.0", default-features = false, features = [
    "2d",
    "debug",
] }

[workspace.lints.clippy]
all = "warn"
correctness = "deny"
suspicious = "warn"
complexity = "warn"
nursery = "warn"
perf = "warn"
style = "warn"
pedantic = { level = "warn", priority = -1 }
new-ret-no-self = { level = "allow", priority = 1 }
type-complexity = { level = "allow", priority = 1 }
match-wildcard-for-single-variants = { level = "allow", priority = 1 }
enum-variant-names = { level = "allow", priority = 1 }

[[example]]
name = "basic"
path = "examples/basic/main.rs"
resolver = "3"
required-features = ["target", "utility"]

[features]
target = []
utility = []
default = ["target", "utility"]
