[package]
name = "utility_goap_internal"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_app = { version = "0.18.0" }
bevy_ecs = { version = "0.18.0" }
bevy_reflect = { version = "0.18.0" }
bevy-trait-query = "0.18.0"
thiserror = "2.0.17"
inventory = "0.3.21"

[features]
default = ["target"]
target = []
