[package]
name = "ergoap_macros"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "ai", "goap", "utility", "target", "macros"]
categories = ["game-development"]
repository = "https://github.com/isidornygren/ergoap"
description = "Macros for the ergoap project"
readme = "README.md"

[dependencies]
proc-macro-crate = "3.4.0"
proc-macro2 = "1.0.105"
quote = "1.0.43"
syn = "2.0.114"

[lib]
proc-macro = true
