//! # Utility GOAP
//!
//! A Goal-Oriented Action Planning (GOAP) library with utility-based scoring for the Bevy game engine.
//!
//! This crate provides a flexible framework for AI decision-making that combines GOAP planning
//! with utility-based scoring to help entities dynamically select and execute actions to achieve goals.
//!
//! ## Features
//!
//! - **GOAP Planning**: Automatic action planning using A* pathfinding to find optimal action sequences
//! - **Utility Scoring**: Score and prioritize goals based on current world state (with `utility` feature)
//! - **Target System**: Support for movement and targeting mechanics (with `target` feature)
//! - **Bevy Integration**: Seamless integration with Bevy's ECS and scheduling systems
//! - **Automatic Registration**: Trait-based component registration for sensors and actions
//!
//! ## Core Concepts
//!
//! - **Sensors**: Components that observe the world state and provide values for planning
//! - **Actions**: Discrete behaviors with preconditions and effects on the world state
//! - **Goals**: Desired world states that the planner tries to achieve
//! - **Plans**: Sequences of actions generated by the A* planner to satisfy goals
//!
//! ## Quick Start
//!
//! ```ignore
//! use bevy::prelude::*;
//! use utility_goap::prelude::*;
//!
//! fn main() {
//!     App::new()
//!         .add_plugins(UtilityGoapPlugin)
//!         .run();
//! }
//! ```
//!
//! ## Schedules
//!
//! The plugin adds two custom schedules that run during the fixed timestep:
//! - [`SensorUpdate`]: Collects sensor values from the world
//! - [`Planning`]: Generates action plans based on current sensor state and goals

use bevy_app::{App, First, FixedMainScheduleOrder, FixedUpdate, Plugin};
use bevy_ecs::schedule::{IntoScheduleConfigs, ScheduleLabel};
use bevy_ecs::world::World;
use plan::make_plan;
use world_sensor::collect_sensor_values;

use crate::auto_register::register_trait_types;
#[cfg(feature = "target")]
use crate::target::finish_goto;
#[cfg(feature = "target")]
use bevy_app::FixedPostUpdate;

mod action_provider;
mod astar;
mod auto_register;
mod comparison;
mod current_action;
mod effect;
mod goal;
mod id_container;
mod plan;
mod sensor_state;
#[cfg(feature = "target")]
mod target;
#[cfg(feature = "utility")]
mod utility;
mod world_sensor;

pub use crate::action_provider::{ActionProvider, ActionProviderBuilder, ActionProviderTrait};
pub use crate::comparison::Comparison;
pub use crate::current_action::CurrentAction;
pub use crate::goal::Goal;
pub use crate::sensor_state::SensorState;
#[cfg(feature = "target")]
pub use crate::world_sensor::TargetValue;
pub use crate::world_sensor::{
    SensorComparison, SensorComparisonBool, SensorComparisonOption, SensorEffect, SensorValue,
    WorldSensor, WorldSensorValue,
};
pub use auto_register::{AutomaticTraitRegistrations, RegisterComponentAs};
pub use id_container::IdContainer;
#[cfg(feature = "target")]
pub use target::GotoTarget;
#[cfg(feature = "utility")]
pub use utility::{GoalProvider, GoalProviderTrait, Score, Scorer};

pub mod __macro_exports {
    pub use bevy_ecs;
    pub use bevy_trait_query;
    pub use inventory;
}

/// Commonly used types and traits for working with utility-goap.
///
/// This module re-exports the most frequently used types to simplify imports.
pub mod prelude {
    #[cfg(feature = "utility")]
    pub use crate::utility::{GoalProvider, GoalProviderTrait, Score, Scorer};
    pub use crate::{
        Planning, SensorUpdate, UtilityGoapPlugin,
        action_provider::{ActionProvider, ActionProviderBuilder, ActionProviderTrait},
        auto_register::{AutomaticTraitRegistrations, RegisterComponentAs},
        comparison::Comparison,
        current_action::CurrentAction,
        goal::Goal,
        sensor_state::SensorState,
        world_sensor::{
            SensorComparison, SensorComparisonBool, SensorComparisonOption, SensorEffect,
            SensorValue, WorldSensor, WorldSensorValue,
        },
    };
    #[cfg(feature = "target")]
    pub use crate::{target::GotoTarget, world_sensor::TargetValue};
    pub use macros::*;
}

/// Schedule for collecting sensor values from world components.
///
/// This schedule runs after [`FixedUpdate`] and before [`Planning`] in the fixed timestep.
/// Systems in this schedule should update [`SensorState`] components based on world observations.
#[derive(ScheduleLabel, Debug, Clone, PartialEq, Eq, Hash)]
pub struct SensorUpdate;

/// Schedule for generating action plans to achieve goals.
///
/// This schedule runs after [`SensorUpdate`] in the fixed timestep.
/// The planner uses A* pathfinding to find optimal action sequences based on current sensor state.
#[derive(ScheduleLabel, Debug, Clone, PartialEq, Eq, Hash)]
pub struct Planning;

/// Main plugin for the utility-goap framework.
///
/// This plugin sets up the necessary schedules and systems for GOAP planning.
/// Add this to your Bevy app to enable utility-based goal-oriented action planning.
///
/// # Schedules Added
///
/// - [`SensorUpdate`]: Collects sensor values (runs after `FixedUpdate`)
/// - [`Planning`]: Generates action plans (runs after `SensorUpdate`)
///
/// # Systems Added
///
/// - Sensor value collection system (in [`Planning`])
/// - Plan generation system (in [`Planning`])
/// - Trait type registration system (in [`First`])
/// - Target completion system (in `FixedPostUpdate`, with `target` feature)
///
/// # Example
///
/// ```
/// use bevy::prelude::*;
/// use utility_goap::UtilityGoapPlugin;
///
/// App::new()
///     .add_plugins(UtilityGoapPlugin);
/// ```
pub struct UtilityGoapPlugin;

impl Plugin for UtilityGoapPlugin {
    fn build(&self, app: &mut App) {
        app.init_schedule(SensorUpdate).init_schedule(Planning);
        {
            let mut main_schedule_order = app.world_mut().resource_mut::<FixedMainScheduleOrder>();
            main_schedule_order.insert_after(FixedUpdate, SensorUpdate);
            main_schedule_order.insert_after(SensorUpdate, Planning);
        }
        app.add_systems(Planning, (collect_sensor_values, make_plan).chain())
            .add_systems(First, |world: &mut World| register_trait_types(world));
        #[cfg(feature = "target")]
        app.add_systems(FixedPostUpdate, finish_goto);
    }
}
