//! Plan generation and execution system.
//!
//! This module handles the creation and execution of action plans. When sensor state changes,
//! the planner uses A* search to find optimal action sequences to achieve goals.

use bevy_ecs::{
    component::Component,
    entity::Entity,
    lifecycle::HookContext,
    query::Changed,
    system::{Commands, Query},
    world::{DeferredWorld, Ref},
};

use crate::{
    action_provider::ActionProviderTrait, astar::astar_plan, current_action::CurrentActionCommands,
    goal::Goal, sensor_state::SensorState,
};

/// Hook function called when a [`Plan`] is inserted on an entity.
///
/// This automatically pops the first action from the plan and spawns it as the
/// current action. Subsequent actions will be executed as previous actions complete.
pub fn on_insert_plan(mut world: DeferredWorld, HookContext { entity, .. }: HookContext) {
    if let Some(first_action) = world
        .get_mut::<Plan>(entity)
        .and_then(|mut plan| plan.0.pop())
    {
        world
            .commands()
            .entity(entity)
            .spawn_current_action(first_action);
    }
}

/// A sequence of actions planned to achieve a goal.
///
/// Plans are generated by the A* planner and stored in reverse order (last action first).
/// When inserted, the plan automatically spawns the first action. The plan component
/// should be managed by the planning system and not modified directly.
///
/// # Implementation Note
///
/// Actions are stored in reverse order to allow efficient popping from the end of the vector.
#[derive(Component)]
#[component(on_insert=on_insert_plan)]
pub struct Plan(Vec<Box<dyn ActionProviderTrait>>);

/// System that generates action plans when sensor state changes.
///
/// This system runs in the [`Planning`] schedule and creates plans for entities with goals.
/// It queries entities with changed sensor state and uses A* pathfinding to find optimal
/// action sequences to achieve their goals.
///
/// # Behavior
///
/// - Only processes entities where [`SensorState`] has changed
/// - Collects all available [`ActionProviderTrait`] components on the entity
/// - Uses A* search to find the lowest-cost action sequence
/// - Inserts a [`Plan`] component if a valid plan is found
/// - Removes the plan and current action if no valid plan exists
///
/// # Performance
///
/// The system only runs when sensor state changes, minimizing unnecessary replanning.
///
/// [`Planning`]: crate::Planning
pub fn make_plan(
    mut commands: Commands,
    query: Query<(Entity, &SensorState, &dyn ActionProviderTrait, &Goal), Changed<SensorState>>,
) {
    for (entity, sensor_values, actions, goal) in query.iter() {
        let dyn_actions: Vec<&dyn ActionProviderTrait> =
            actions.iter().map(Ref::into_inner).collect();
        if let Some(plan) = astar_plan(&sensor_values.to_owned(), &dyn_actions, goal) {
            let plan_actions = plan
                .into_iter()
                .filter_map(|index| dyn_actions.get(index))
                .map(|action| action.clone_box())
                .rev()
                .collect();

            commands.entity(entity).insert(Plan(plan_actions));
        } else {
            commands
                .entity(entity)
                .remove::<Plan>()
                .despawn_current_action();
        }
    }
}
