on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
name: CI

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run cargo test
        run: cargo test --all-features
  clippy_check:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          components: clippy
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          components: rustfmt
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  bench:
    name: Benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      deployments: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run benchmarks
        run: cargo bench --all-features -- --output-format bencher | tee output.txt
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "cargo"
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false
          alert-threshold: "200%"
          comment-on-alert: true
