on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
name: CI

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      deployments: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          components: clippy, rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      - name: Run tests
        run: cargo test --all-features
      - name: Run benchmarks
        run: cargo bench --all-features -- --output-format bencher | tee output.txt
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "cargo"
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false
          alert-threshold: "200%"
          comment-on-alert: true
